<a href="https://colab.research.google.com/github/25Alisha/lab1/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_1_%D0%91%D0%BE%D0%BD%D0%B4%D0%B0%D1%80%D0%B5%D0%B2%D0%B0_%D0%90_%D0%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторная работа № 1 по дисциплине "Технологии Big Data"**

*Выполнила студентка 1 курса магистратуры направления "Банковские информационные технологии"*

Бондарева Алина Владимировна

***Описание датасета***

Датасет "house" состоит из 7 столбцов, к которым относятся:


1.   index - порядковый номер позиции в таблице;
2.   SquareFeet - квадратный фут (единица измерения площади в английской системе мер, «международный» фут стал равняться в точности 0,3048 м);
3.   Bedrooms - количество спальных комнат;
4.   Bathrooms - количество ванных комнат;
5.   Neighborhood - район (Rural - сельский, Suburb - пригородный, Urban - городской);
6.   YearBuilt - год постройки;
7.   Price - стоимость дома ($).

Импорт библиотек и чтение датасета

In [3]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive',force_remount=True)
df = pd.read_csv('drive/MyDrive/house.csv')
df=df.reset_index()
df

Mounted at /content/drive

,index,SquareFeet,Bedrooms,Bathrooms,Neighborhood,YearBuilt,Price
0,0,2126,4,1,Rural,1969,215355.283618
1,1,2459,3,2,Rural,1980,195014.221626
2,2,1860,2,1,Suburb,1970,306891.012076
3,3,2294,2,1,Urban,1996,206786.787153
4,4,2130,5,2,Suburb,2001,272436.239065
...,...,...,...,...,...,...,...
1002,1002,1797,4,2,Suburb,1999,234486.012407
1003,1003,2265,5,2,Suburb,1955,165566.968885
1004,1004,2274,3,3,Suburb,1992,286489.719599
1005,1005,1876,4,3,Rural,2005,177401.462731
1006,1006,2028,3,2,Rural,1966,249908.628547

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         1007 non-null   int64
 1   SquareFeet    1007 non-null   int64
 2   Bedrooms      1007 non-null   int64
 3   Bathrooms     1007 non-null   int64
 4   Neighborhood  1007 non-null   object
 5   YearBuilt     1007 non-null   int64
 6   Price         1007 non-null   float64
dtypes: float64(1), int64(5), object(1)
memory usage: 55.2+ KB

In [5]:
#Преобразование столбца "Price" из вещественного в целочисленный формат
df['Price'] = df['Price'].astype (int)
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         1007 non-null   int64
 1   SquareFeet    1007 non-null   int64
 2   Bedrooms      1007 non-null   int64
 3   Bathrooms     1007 non-null   int64
 4   Neighborhood  1007 non-null   object
 5   YearBuilt     1007 non-null   int64
 6   Price         1007 non-null   int64
dtypes: int64(6), object(1)
memory usage: 55.2+ KB

      index  SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt   Price
0         0        2126         4          1        Rural       1969  215355
1         1        2459         3          2        Rural       1980  195014
2         2        1860         2          1       Suburb       1970  306891
3         3        2294         2          1        Urban       1996  206786
4         4        2130         5          2       Suburb       2001  272436
...     ...         ...       ...        ...          ...        ...     ...
1002   1002        1797         4          2       Suburb       1999  234486
1003   1003        2265         5          2       Suburb       1955  165566
1004   1004        2274         3          3       Suburb       1992  286489
1005   1005        1876         4          3        Rural       2005  177401
1006   1006        2028         3          2        Rural       1966  249908

[1007 rows x 7 columns]

Предположим, что мы хотим найти среднюю цену домов, построенных после 2000 года, с квадратурой от 1200 до 1800 квадратных футов и с количеством спальных комнат не менее 3. Для этого мы можем использовать map для преобразования данных и reduce для вычисления средней цены.

In [19]:
# Функция Map
def map_function(df):
    filtered_prices = []
    for index, row in df.iterrows():
        if (row["YearBuilt"] > 2000 and
            1200 <= row["SquareFeet"] <= 1800 and
            row["Bedrooms"] >= 3):
            filtered_prices.append(row["Price"])
    return filtered_prices

# Функция Reduce
def reduce_function(mapped_data):
    if not mapped_data:
        return None
    total_price = sum(mapped_data)
    count_houses = len(mapped_data)
    return total_price / count_houses if count_houses > 0 else None

# Применяем функции Map и Reduce
mapped_data = map_function(df)
average_price = reduce_function(mapped_data)

print("Средняя цена домов, построенных после 2000 года, с квадратурой от 1200 до 1800 квадратных футов и с количеством спален не менее 3:",
      round(average_price,2),"долларов.")

Средняя цена домов, построенных после 2000 года, с квадратурой от 1200 до 1800 квадратных футов и с количеством спален не менее 3: 176164.13 долларов.